name = "GamersWarfared"
author = "Gamers"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d03be410ce3fd3029f44a90d7ef719bb94ad9def06df0994a313da150bbbcb2"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
