name = "GamersWarfared"
author = "Gamers"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfb79bb547771d0068e1b196b5bcd74f815ec1ac4a301ae4ebd7600772019f80"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
