name = "GamersWarfared"
author = "Gamers"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e18adcf1de52bb10b380cd9fe2ce01fb839d48a0a9696cd52bfa441a4c746c8"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"

[options]
no-internal-hashes = "true"
